###########
# site.title

title:    'Tron Researchers'
subtitle: 'CS 175: Project in AI (in ColosseumRL)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-cayman
